### PR TITLE
#1598 Fix Data View table view and Linked Applications

### LINKED ISSUE #1598: Mobile -- Data View details page formatting
It's not great, currently.

Image

- Table styling
- Implement Table Label Wrapper on "Linked Applications" section
- Hide "Linked Applications" section if none present

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #1598 

Styles for Data View details page:

Screen Shot 2023-11-07 at 14 11 52 copy

### CODE REVIEW

File: src/containers/DataDisplay/DataViewTable.tsx [hunk 1]
```diff
@@ -96,7 +96,7 @@ const DataViewTable: React.FC<{ codeFromLookupTable?: string }> = ({ codeFromLoo
           </div>
         )}
         <div className="flex-row-space-between-center" style={{ width: '100%' }}>
-          <div className="flex-column" style={{ gap: 5 }}>
+          <div className="flex-column" style={{ width: '100%', gap: 5 }}>
```
Comment (CarlosNZ) [inline src/containers/DataDisplay/DataViewTable.tsx:99]: Unrelated fix for a regresssion I noticed.

File: src/containers/DataDisplay/ApplicationLinks.tsx
Comment (guatemartin) [inline src/containers/DataDisplay/ApplicationLinks.tsx:1]: I don't seem to be able to find an example with a Linked Application.  I can't see anything in the code to worry about though.

**Review by guatemartin — APPROVED** [review]

File: src/containers/DataDisplay/ApplicationLinks.tsx
Comment (CarlosNZ) [reply src/containers/DataDisplay/ApplicationLinks.tsx:1]: Hmm, if you're using the Angola snapshot, then most of the Data View entries will have linked applications.

For example:
- http://localhost:3000/data/user/54 
- http://localhost:3000/data/organisation/4 
- http://localhost:3000/data/product/4 

Can you just confirm these work for you?
